version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    build: api/.
    restart: always
    ports:
      - 5000:5000
  web:
    build: web/.
    restart: always
    ports:
      - 80:80
